---
- name: Configure MySQL on CentOS
  gather_facts: no
  hosts: linux
  become: yes

  tasks:
    - name: Start and enable MySQL service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Secure MySQL installation
      expect:
        command: mysql_secure_installation
        responses:
          'Press y|Y for Yes, any other key for No:': 'y'
          'Please enter 0 = LOW, 1 = MEDIUM and 2 = STRONG:': '0'
          'New password:': "'{{ mysql_password }}'"
          'Re-enter new password:': "'{{ mysql_password }}'"
          'Do you wish to continue with the password provided?(Press y|Y for Yes, any other key for No) :': 'y'
          'Remove anonymous users? (Press y|Y for Yes, any other key for No) :': 'y'
          'Disallow root login remotely? (Press y|Y for Yes, any other key for No) :': 'y'
          'Remove test database and access to it? (Press y|Y for Yes, any other key for No) :': 'y'
          'Reload privilege tables now? (Press y|Y for Yes, any other key for No) : ': 'y'

    - name: Create MySQL database and user
      community.mysql.mysql_db:
        name: '{{ database_name }}'
        state: present
      become: true

    - name: Create MySQL user
      community.mysql.mysql_user:
        name: '{{ database_user }}'
        password: '{{ database_password }}'
        priv: '{{ database_name }}.*:ALL'
        host: localhost
        state: present

