---
- name: Leggi e mostra il contenuto di un file
  hosts: linux
  gather_facts: false

  tasks:
    - name: Scrivi il contenuto in un nuovo file localmente 
      ansible.builtin.copy:
        src: /etc/passwd
        dest: /tmp/awx/ansible_file.txt



    - name: Fetch file from remote host to localhost
      fetch:
        src: /etc/passwd
        dest: /tmp/




