---
- name: Leggi e mostra il contenuto di un file
  hosts: linux
  gather_facts: false

  tasks:
    - name: Scrivi il contenuto in un nuovo file
      ansible.builtin.copy:
        src: /etc/passwd
        dest: /tmp/ansible_file.txt



    - name: Fetch file
      fetch:
        src: /etc/passwd
        dest: /tmp/




