---
- name: Read JSON file and take action
  hosts: linux
  gather_facts: no
  tasks:
    - name: Read JSON file
      ansible.builtin.fetch:
        src: /tmp/file_json.json
        dest: /tmp/
        flat: yes

    - name: Load Variables
      ansible.builtin.include_vars:
        file: /tmp/awx/file_json.json
      delegate_to: localhost

    - name: Debug Directory Content
      ansible.builtin.shell: ls -la /tmp/awx/
        delegate_to: localhost

    - name: Mostra tutte le informazioni dal file JSON
      debug:
        var: file_json
