---
- name: Read JSON file and take action
  hosts: linux
  gather_facts: no
  tasks:
    - name: Read JSON file
      ansible.builtin.fetch:
        src: /tmp/external_data.json
        dest: /tmp/

    - name: Mostra tutte le informazioni dal file JSON
      debug:
        var: external_data
