---
- name: Read JSON file and take action
  hosts: linux
  gather_facts: no
  tasks:
    - name: Read JSON file
      ansible.builtin.fetch:
        src: /tmp/file_json.json
        dest: /tmp/{{ inventory_hostname }}-file_json.json
        flat: yes

    - name: Load Variables
      ansible.builtin.include_vars:
        file: /tmp/{{ inventory_hostname }}-file_json.json
      register: file_json
      delegate_to: localhost

    - name: Mostra tutte le informazioni dal file JSON
      debug:
        var: file_json
      delegate_to: localhost

    - name: Extract IP from JSON
      debug:
        var: file_json.ansible_facts.router.ip 
      delegate_to: localhost
