---
- name: Read JSON file and take action
  hosts: linux
  gather_facts: no
  become: yes
  tasks:
    - name: Read JSON file from remote host
      ansible.builtin.fetch:
        src: /tmp/file_json.json
        dest: /tmp/{{ inventory_hostname }}-file_json.json
        flat: yes

    - name: Load Variables into register
      ansible.builtin.include_vars:
        file: /tmp/{{ inventory_hostname }}-file_json.json
      register: file_json
      delegate_to: localhost

    - name: Output file JSON
      debug:
        var: file_json

    - name: Extract IP from JSON
      debug:
        var: file_json.ansible_facts.router.ip 
      register: ip 
      when: file_json.ansible_facts.router.ip is defined

    - name: Execute PING on IP extracted
      ansible.builtin.shell:
        cmd: 'ping -c 4 "{{ file_json.ansible_facts.router.ip }}"'
      register: ping_out

    - name: Output ping if successful
      debug:
        var: ping_out.stdout_lines
      when: ping_out.rc == 0


    - name: Check if ping was successful
      set_fact:
        ip_reachable: "{{ ping_out.rc == 0 }}"

    - name: Output result ip list
      debug:
        msg: "IP {{ file_json.ansible_facts.router.ip }} is {{ 'reachable' if ip_reachable else 'unreachable' }}"
      register: ip_list_out

    - name: Check if file is present
      ansible.builtin.command:
        cmd: ls /tmp/ip_list_reachable
      register: ls_result
      ignore_errors: yes
      delegate_to: localhost
      run_once: true

    - name: Create new file in /tmp/ named ip_list_reachable
      ansible.builtin.command:
        cmd: touch /tmp/ip_list_reachable
      delegate_to: localhost
      run_once: true
      when: ls_result.rc != 0

    - name: Write ip reachable on file
      ansible.builtin.lineinfile:
        line: "{{ ip_list_out.msg }}"
        path: /tmp/ip_list_reachable
        mode: 0644
        owner: awx
        group: awx
        insertafter: EOF
      delegate_to: localhost







