---
- name: Read JSON file and take action
  hosts: linux
  gather_facts: no
  tasks:
    - name: Read JSON file
      ansible.builtin.fetch:
        src: /tmp/file_json.json
        dest: /tmp/{{ inventory_hostname }}-file_json.json
        flat: yes

    - name: Load Variables
      ansible.builtin.include_vars:
        file: /tmp/{{ inventory_hostname }}-file_json.json
      register: file_json
      delegate_to: localhost

    - name: Mostra tutte le informazioni dal file JSON
      debug:
        var: file_json

    - name: Extract IP from JSON
      debug:
        var: file_json.ansible_facts.router.ip 
      register: ip 
      when: file_json.ansible_facts.router.ip is defined

    - name: Execute PING on IP
      ansible.builtin.shell:
        cmd: 'ping -c 4 "{{ file_json.ansible_facts.router.ip }}"'
      register: ping_out

    - name: Output ping
      debug:
        var: ping_out.stdout_lines
      when: ping_out.rc == 0


    - name: Check if ping was successful
      set_fact:
        ip_reachable: "{{ ping_out.rc == 0 }}"

    - name: Output result
      debug:
        msg: "IP {{ file_json.ansible_facts.router.ip }} is {{ 'reachable' if ip_reachable else 'unreachable' }}"
      register: ip_list_out

    - name: Write ip reachable on file
      ansible.builtin.lineinfile:
        path: /tmp/ip_list_reachable
        line: "{{ ip_list_out | to_nice_json }}"
      delegate_to: localhost
