---
- name: Read JSON file and take action
  hosts: linux
  gather_facts: no
  tasks:
    - name: Read JSON file
      ansible.builtin.fetch:
        src: /tmp/file_json.json
        dest: /tmp/
        flat: yes

- name: Swtich inventory to take action from localhost
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Load Variables
      ansible.builtin.include_vars:
        file: /tmp/file_json.json
      register: file_json


    - name: Mostra tutte le informazioni dal file JSON
      debug:
        var: file_json
