---
- name: Read JSON file and take action
  hosts: linux
  gather_facts: no
  tasks:
    - name: Read JSON file
      ansible.builtin.fetch:
        src: /tmp/file_json.json
        dest: /tmp/
        flat: yes

- name: Swtich inventory to take action from localhost
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Load Variables
      ansible.builtin.include_vars:
        file: /tmp/file_json.json
      register: file_json

    - name: Mostra tutte le informazioni dal file JSON
      debug:
        var: file_json
    
    - name: Download JSON content play
      uri:
        url: https://jsonplaceholder.typicode.com/users
        return_content: yes
      register: jsoncontent


    - name: Business Card
      debug: 
        msg: "{{ jsoncontent.json | json_query(jmesquery) }}"
      vars:
        jmesquery: "[*].{Name: name, Email: email, Phone: phone, CompanyName: company.name, WebSite: website, City: address.city}"
