---
- name: Uninstall {{ package_name }}
  hosts: windows
  gather_facts: no
  tasks:
    - name: Uninstall {{ package_name }}
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ package_name }}"
        state: absent
        ignore_checksums: yes
        
