---
- name: gns3 cisco router
  hosts: router
  gather_facts: no
  tasks:
    - name: Check the startup-config against the running-config
      cisco.ios.ios_config:
        diff_against: startup
        diff_ignore_lines:
          - ntp clock .*
    
    - name: get timestamp
      command: date +%Y%m%d-%H-%M-%S
      register: timestamp
      
    - name: backup ios config
      ios_config:
       backup: yes
       backup_options:
         filename: "running-config-{{ timestamp.stdout }}"
         dir_path: "/tmp/{{ inventory_hostname }}"






