---
- name: Configure Loopback Interface
  hosts: router
  gather_facts: no
  
  tasks:
    - name: Configura interfaccia loopback
      ios_command:
        commands:
          - "conf t"
          - "interface loopback{{ loopback_interface }}"
          - "ip address {{ loopback_ip_address }} {{ loopback_subnet_mask }}"
          - "no shutdown"


    - name: Configure interface settings
      cisco.ios.ios_config:
        lines:
          - description test interface
          - ip address 10.10.11.100 255.255.255.0
        parents:
          - interface Loopback888
